#!/usr/bin/env bash

set -ueo pipefail

TOP_PROJECTS=()

# SIRIUS_DIAG
SIRIUS_DIAG_PREFIX="SIRIUS_DIAG"
SIRIUS_DIAG_GIT_URL="https://github.com"
SIRIUS_DIAG_ORG="lnls-dig"
SIRIUS_DIAG_PROJECT="sirius-diagnostics-epics-screens"
SIRIUS_DIAG_TAG="master"
SIRIUS_DIAG_OPI_DIR="op/opi"

TOP_PROJECTS+=("${SIRIUS_DIAG_PREFIX}")

PROJECTS=()

# BPM will me merged to SIRIUS_BPM
BPM_PREFIX="BPM"
BPM_GIT_URL="https://github.com"
BPM_ORG="lnls-dig"
BPM_PROJECT="bpm-epics-ioc"
BPM_TAG="v2.7.11"
BPM_OPI_DIR="op/opi"

# Timing RX will me merged to SIRIUS_BPM
TIM_RX_PREFIX="TIM_RX"
TIM_RX_GIT_URL="https://github.com"
TIM_RX_ORG="lnls-dig"
TIM_RX_PROJECT="tim-rx-epics-ioc"
TIM_RX_TAG="devel"
TIM_RX_OPI_DIR="op/opi"

PROJECTS+=("${TIM_RX_PREFIX}")

# MTCA_IPMI
MTCA_IPMI_PREFIX="MTCA_IPMI"
MTCA_IPMI_GIT_URL="https://gitlab.cnpem.br"
MTCA_IPMI_ORG="DIG"
MTCA_IPMI_PROJECT="mtca-ipmi-epics-ioc"
MTCA_IPMI_TAG="master"
MTCA_IPMI_OPI_DIR="op/opi"

PROJECTS+=("${MTCA_IPMI_PREFIX}")

# Sirius BPM
SIRIUS_BPM_PREFIX="SIRIUS_BPM"
SIRIUS_BPM_GIT_URL="https://github.com"
SIRIUS_BPM_ORG="lnls-dig"
SIRIUS_BPM_PROJECT="sirius-bpm-epics-screens"
SIRIUS_BPM_TAG="master"
SIRIUS_BPM_OPI_DIR="op/opi"

PROJECTS+=("${SIRIUS_BPM_PREFIX}")

# RSFSX
RSFSX_PREFIX="RSFSX"
RSFSX_GIT_URL="https://github.com"
RSFSX_ORG="lnls-dig"
RSFSX_PROJECT="rsfsx-epics-ioc"
RSFSX_TAG="master"
RSFSX_OPI_DIR="op/opi"

PROJECTS+=("${RSFSX_PREFIX}")

# VALON5009
VALON5009_PREFIX="VALON5009"
VALON5009_GIT_URL="https://github.com"
VALON5009_ORG="lnls-dig"
VALON5009_PROJECT="valon5009-epics-ioc"
VALON5009_TAG="devel"
VALON5009_OPI_DIR="op/opi"

PROJECTS+=("${VALON5009_PREFIX}")

# INJ_EFF
INJ_EFF_PREFIX="INJ_EFF"
INJ_EFF_GIT_URL="https://github.com"
INJ_EFF_ORG="lnls-dig"
INJ_EFF_PROJECT="inj-efficiency-epics-ioc"
INJ_EFF_TAG="devel"
INJ_EFF_OPI_DIR="op/opi"

PROJECTS+=("${INJ_EFF_PREFIX}")

# TUNE
TUNE_PREFIX="TUNE"
TUNE_GIT_URL="https://github.com"
TUNE_ORG="lnls-dig"
TUNE_PROJECT="tune-epics-ioc"
TUNE_TAG="devel"
TUNE_OPI_DIR="op/opi"

PROJECTS+=("${TUNE_PREFIX}")

# SCREEN
SCREEN_PREFIX="SCREEN"
SCREEN_GIT_URL="https://github.com"
SCREEN_ORG="lnls-dig"
SCREEN_PROJECT="screen-epics-ioc"
SCREEN_TAG="devel"
SCREEN_OPI_DIR="op/opi"

PROJECTS+=("${SCREEN_PREFIX}")

# BASLER_ACA130075GM
BASLER_ACA130075GM_PREFIX="BASLER_ACA130075GM"
BASLER_ACA130075GM_GIT_URL="https://github.com"
BASLER_ACA130075GM_ORG="lnls-dig"
BASLER_ACA130075GM_PROJECT="basler-acA1300-75gm-epics-ioc"
BASLER_ACA130075GM_TAG="devel"
BASLER_ACA130075GM_OPI_DIR="op/opi"

PROJECTS+=("${BASLER_ACA130075GM_PREFIX}")

# ARAMP
ARAMP_PREFIX="ARAMP"
ARAMP_GIT_URL="https://github.com"
ARAMP_ORG="lnls-dig"
ARAMP_PROJECT="ar-amp-epics-ioc"
ARAMP_TAG="master"
ARAMP_OPI_DIR="op/opi"

PROJECTS+=("${ARAMP_PREFIX}")

# DIFF_CTRL
DIFF_CTRL_PREFIX="DIFF_CTRL"
DIFF_CTRL_GIT_URL="https://github.com"
DIFF_CTRL_ORG="lnls-dig"
DIFF_CTRL_PROJECT="diff-ctrl-epics-ioc"
DIFF_CTRL_TAG="devel"
DIFF_CTRL_OPI_DIR="op/opi"

PROJECTS+=("${DIFF_CTRL_PREFIX}")

# DMM7510
DMM7510_PREFIX="DMM7510"
DMM7510_GIT_URL="https://github.com"
DMM7510_ORG="lnls-dig"
DMM7510_PROJECT="dmm7510-epics-ioc"
DMM7510_TAG="devel"
DMM7510_OPI_DIR="op/opi"

PROJECTS+=("${DMM7510_PREFIX}")

# DMC30017
DMC30017_PREFIX="DMC30017"
DMC30017_GIT_URL="https://github.com"
DMC30017_ORG="lnls-dig"
DMC30017_PROJECT="galil-dmc30017-epics-ioc"
DMC30017_TAG="devel"
DMC30017_OPI_DIR="op/opi"

PROJECTS+=("${DMC30017_PREFIX}")

# AGILENT33521A
AGILENT33521A_PREFIX="AGILENT33521A"
AGILENT33521A_GIT_URL="https://github.com"
AGILENT33521A_ORG="lnls-dig"
AGILENT33521A_PROJECT="agilent33521a-epics-ioc"
AGILENT33521A_TAG="devel"
AGILENT33521A_OPI_DIR="op/opi"

PROJECTS+=("${AGILENT33521A_PREFIX}")

# SINAP_TIMING
SINAP_TIMING_PREFIX="SINAP_TIMING"
SINAP_TIMING_GIT_URL="https://github.com"
SINAP_TIMING_ORG="lnls-dig"
SINAP_TIMING_PROJECT="sinap-timing-epics-ioc"
SINAP_TIMING_TAG="86bfcade6a22f945e230d1658ce7f165c9ee0be3"
SINAP_TIMING_OPI_DIR="op/opi"

PROJECTS+=("${SINAP_TIMING_PREFIX}")

# RSSMX100A
RSSMX100A_PREFIX="RSSMX100A"
RSSMX100A_GIT_URL="https://github.com"
RSSMX100A_ORG="lnls-dig"
RSSMX100A_PROJECT="rssmx100a-epics-ioc"
RSSMX100A_TAG="master"
RSSMX100A_OPI_DIR="op/opi"

PROJECTS+=("${RSSMX100A_PREFIX}")

# RF System
RFSYSTEM_PREFIX="RFSYSTEM"
RFSYSTEM_GIT_URL="https://gitlab.cnpem.br"
RFSYSTEM_ORG="david.daminelli"
RFSYSTEM_PROJECT="RF_System_CSS"
RFSYSTEM_TAG="a760d4d845d5d63562979cba975588b8f38b102f"
RFSYSTEM_OPI_DIR="opis"
RFSYSTEM_DEST_PROJECT_NAME="rf-system-epics-ioc"

PROJECTS+=("${RFSYSTEM_PREFIX}")

# RF System
LLRF_PREFIX="LLRF"
LLRF_GIT_URL="https://gitlab.cnpem.br"
LLRF_ORG="con"
LLRF_PROJECT="dllrf-css-screens"
LLRF_TAG="7f1d58856e8cb431405af93e594bd26a470e109e"
LLRF_OPI_DIR="opis"
LLRF_DEST_PROJECT_NAME="llrf-epics-ioc"

PROJECTS+=("${LLRF_PREFIX}")

# RF System
RAD_PREFIX="RAD"
RAD_GIT_URL="https://gitlab.cnpem.br"
RAD_ORG="con"
RAD_PROJECT="radiation-probes-opi"
RAD_TAG="master"
RAD_OPI_DIR=""
RAD_DEST_PROJECT_NAME="rad-mon-epics-ioc"

PROJECTS+=("${RAD_PREFIX}")

##################### Merge OPI Folders

MERGE_PROJECTS=()

BPM_MERGE_PREFIX="BPM_MERGE"
BPM_MERGE_REPOS_PREFIX=()
BPM_MERGE_REPOS_PREFIX+=("BPM")
BPM_MERGE_REPOS_PREFIX+=("SIRIUS_BPM")
BPM_MERGE_DEST_PREFIX="SIRIUS_BPM"

MERGE_PROJECTS+=("${BPM_MERGE_PREFIX}")
